name: Nightly Synthetic Data Generator

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # 2:00 AM UTC daily

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Generate synthetic data
        run: |
          python generate_synthetic.py --input demo_clinical_dataset.csv --output synthetic_output_nightly.csv

      - name: Commit new synthetic data
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin main
          git add synthetic_output_nightly.csv
          git commit -m "Nightly synthetic data update" || echo "No changes to commit"
          git push origin HEAD:main
