name: Nightly Synthetic Data Generator

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2:00 AM UTC daily
  workflow_dispatch:     # Allows manual runs too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Synthetic Data Generator
        run: |
          python generate_synthetic.py --input demo_clinical_dataset.csv --output synthetic_output_nightly.csv

      - name: Commit updated synthetic data
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add synthetic_output_nightly.csv
          git commit -m "Nightly synthetic data update"
          git push
